version: '3.3'
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    image: nikitakaz/foodgram:v1.0.0 
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0:8000 foodgram.wsgi"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    #ports:
    # - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: nikitakaz/foodgram_front:v1.0.0
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media
    depends_on:
      - web
volumes:
  static_value:
  media_value:
  postgres_data: