# Generated by Django 4.1.7 on 2023-03-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
