# Generated by Django 4.1.7 on 2023-04-10 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0010_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('author', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('author', 'recipe')},
        ),
    ]
