# Generated by Django 4.1.7 on 2023-03-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('username',)},
        ),
    ]
